language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
  - php: hhvm

sudo: true

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - sudo sed -i 's/#$ModLoad imudp/$ModLoad imudp/' /etc/rsyslog.conf
  - sudo sed -i 's/#$UDPServerRun 514/$UDPServerRun 514/' /etc/rsyslog.conf
  - sudo service rsyslog restart
  - sudo chmod +r /var/log/syslog
  - vendor/bin/phpunit --verbose --coverage-text

notifications:
  slack:
    secure: fYgc+YVeHVTl7NRoUlDAIGgULnV/RUm+wwpGbdYm5NE2sMn+CeUaaj6wA/A6ZJkULn7r/OxSHRSO3/KH8lV72Ok2GxC2+69DB88m7RnCzOl7VeZkNIjSWFUP1PQkgkJbx0uMRtpYT17iYsjzKMkB7owUoOHKiRJV3J+rGnscgh2kfTIaAfJgK5XDBizocpyDPHgzQOiVreEM1C0dnKqVh0vsKkogGDiC2AT2zL0RIgcCzowlMBRMr77A2kU4YGQS+lRu6IfWKnU5TinjZi6lIeSJOULAieBXNZ3SEz6CE90JJyTbXh30OT3GI5mMdX7d/4+kw5nKLG0Xy6e0olZq/e9xVYo8e+D7dRWqZD0vxmuJEobfsKR3WS6580GFWtOKQZPha0PXxbDtffP7+RCDpg8bEt+CuQkr8DXfxZIh7C5166/gbCPp7OFkDJi6PsBGrh5RFTchwduUDhO6Sc8gVU8YGDNQl1Smlt9WuaxWrcndfsfvcRZ5zp2nc0cGD2hWgAenL6WrfikqOWWAiZKaw1E4mYdMEBhiAfa7u818WdSLc269O6PlqdnGm22PAY2+ZPYa/5IugujwDOAviS1hsjlrthVRNWoNlx2k/7kZJ6P1v+F4mit+xbKfyCKLAaDogwd9btg+kevXsY5oYeHTi3VF4+ZFBjzbYF/+WzuPB74=
